### ISSUE TITLE
Merge with / deprecate in favor of upstream Heroku static buildpack?

### ISSUE THREAD

**Issue by callahad** [dokku/heroku-buildpack-nginx#19]
Looks like there's a Heroku-maintained static buildpack at https://github.com/heroku/heroku-buildpack-static

I haven't dug into it at all, but it might be worth investigating as an alternative to maintaining a separate one for Dokku.

**Comment by josegonzalez** [comment]
Seems its pretty different from this one. Is it officially supported on heroku?

**Comment by callahad** [comment]
I've had a chance to use it now, and it's less different than it seems at first. More configurable, but it fundamentally does the same thing.

As to official support, from https://github.com/heroku/heroku-buildpack-static/issues/49:

> We're using it in production to power some sites on Heroku. [but] It's not maintained fulltime like our official languages.

**Comment by jalcine** [comment]
I've been debating testing it out. I currently use this buildpack with my site. I might give it a whirl in the week.

**Comment by ctsstc** [comment]
Tried it out, seems to be working great 👌

**Comment by josegonzalez** [comment]
Feel free to use the heroku version if you'd like, Dokku will continue to bundle this one until the one upstream becomes official.
