### ISSUE TITLE
confusing documentation regarding APP_NAME

### ISSUE THREAD

**Issue by mrooney** [dokku/heroku-buildpack-nginx#20]
The README says:

> Add an empty file called .static to your root directory of your web project (regardless if you use a custom value for NGINX_ROOT)
> 
> Where $APP_NAME is your application's name.

The second sentence doesn't seem to make much sense. What APP_NAME? Where does it go? Am I missing something? :)

**Comment by josegonzalez** [comment]
Sorry, old docs. Thats unrelated to anything at this point, it was pointing to the manual way of setting this buildpack.

**Comment by mrooney** [comment]
Thanks for the quick fix :)
