### ISSUE TITLE
Question: Build static files on deploy

### ISSUE THREAD

**Issue by am** [dokku/heroku-buildpack-nginx#28]
How can I generate/build the files on the deploy? I've a static web application, to generate the files I depende on node. I would like to execute a node script that generate those static files that can then be server with NGNIX.

Thank you

**Comment by josegonzalez** [comment]
You would need to use two different buildpacks - both the nodejs and this one - in order to do so. Typically you use a `.buildpacks` file or similar to specify multiple buildpacks.

If you are using dokku, please see the buildpack documentation to see how to use multiple buildpacks.

**Comment by am** [comment]
Thank you @josegonzalez , I've been playing with that, in the end I could not achieve what I wanted to do, but I understood the idea.

**Comment by jdinartejesus** [comment]
Hello @josegonzalez it's possible to change the build folder? I'm currently using the project with this structure:

```
- app
  - build
  - src
````

I wanted to move the files from build into the folder `/www` instead the full project.

**Comment by josegonzalez** [comment]
This nginx buildpack doesn't build assets, so whatever you use to build them, you'll need to investigate there. Sorry.

**Comment by jdinartejesus** [comment]
Hello @josegonzalez, I actually found the issue. I think isn't clear in the documentation that you need to create variable `NGINX_ROOT` inside of dokku. I was trying to create this on my repo using the file `.env` and that's why wasn't working.

**Comment by josegonzalez** [comment]
@jdinartejesus mind making a pull request with the documentation you think is necessary?
