### ISSUE TITLE
Unable to deploy with dokku buildpacks nginx

### ISSUE THREAD

**Issue by pythdasch** [dokku/heroku-buildpack-nginx#30]
Hi,

I'm trying to deploy a static website following the guide provided on readme.md

<img width="1440" alt="capture d ecran 2018-06-09 a 20 19 46" src="https://user-images.githubusercontent.com/2873224/41194855-8b9b1c12-6c22-11e8-8f45-f67ae21685e7.png">

but when I deploy it just fails:

```
MacBook-Pro-de-david:marthe davidscheck$ git push dokku master
Counting objects: 28, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (24/24), done.
Writing objects: 100% (28/28), 31.15 KiB | 7.79 MiB/s, done.
Total 28 (delta 9), reused 0 (delta 0)
-----> Cleaning up...
-----> Building marthe from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Fetching custom buildpack
To marthewery.be:marthe
 ! [remote rejected] master -> master (pre-receive hook declined)
```

**Comment by josegonzalez** [comment]
Can you show the output of a deploy after running `dokku trace on`?

**Comment by pythdasch** [comment]
https://dpaste.de/mgfJ
thanks :)

**Comment by josegonzalez** [comment]
Can you add a trailing newline to you `.env` file and try another deploy?

**Comment by pythdasch** [comment]
I did and it’s failing

**Comment by josegonzalez** [comment]
Can you show me the contents of your `.env` file, and the logs of a deploy with `dokku trace on` after you added a newline?

**Comment by pythdasch** [comment]
<img width="1440" alt="capture d ecran 2018-06-14 a 18 36 54" src="https://user-images.githubusercontent.com/2873224/41425757-f620ff1a-7001-11e8-927b-29ea6bcd0aa9.png">

and the stack trace 
https://dpaste.de/6ujj

In fact built wasn't finished so now it works fine.

Very strange.

Thanks for your time
