### ISSUE TITLE
Build static files and then serve on deploy

### ISSUE THREAD

**Issue by justintemps** [dokku/heroku-buildpack-nginx#31]
I'm trying to deploy a gatsbyjs app to Digital Ocean via Dokku along the lines suggested by @josegonzalez in #28.

My .buildpack looks like this:

```
https://github.com/heroku/heroku-buildpack-nodejs
https://github.com/dokku/buildpack-nginx
```

I can see in the application logs that the files are successfully being built. However the site itself throws a 500 error.

I can see the requests coming in via `dokku nginx:access-logs myapp` but there are no error messages for those requests `dokku nginx:error-logs myapp`.

Think I'm doing everything else right. I have an (empty) .static file in my root directory and an ENV variable for NGINX_ROOT set to `public/` which is where my static assets are located.

Btw, thanks to all the maintainers for their work on dokku. It's an awesome product--I use it all the time.

**Comment by josegonzalez** [comment]
Can you show the log output of the deploy?

**Comment by justintemps** [comment]
Reading the log output carefully, I realised that in this instance for some reason, my Procfile was being ignored and my static files weren't being built. I've saved the log output [here](https://gist.github.com/justintemps/a64c5df3acdae256a47fb220ac1c6331).

I was able to get it to work by adding this to my package.json scripts:

```
"heroku-postbuild" : "yarn build"
```

Now everything's working fine, I'm just wondering if this is the best way to deploy or if I shouldn't be using postdeploy in app.json as well. I've actually tried that already like this:

```
{
  "scripts": {
    "dokku": {
      "postdeploy": "yarn build"
    }
  }
}
```

and got the following error:

```
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'user@host:dokku-app'
```

**Comment by josegonzalez** [comment]
What do you mean, your Procfile is being ignored?

**Comment by justintemps** [comment]
I mean that I had a Procfile that should have executed the command to build the static files, but it wasn't being called.

**Comment by josegonzalez** [comment]
Procfiles only run on boot. Do you have debug log output from a failing deploy?

**Comment by ariamckinley** [comment]
So I was able to get this working on my [personal blog](https://words.garet.io)

The [repo is here](https://github.com/garetmckinley/words.garet.io) if you'd like to review what I did @justintemps 

I was running into a lot of issues, but what seemed to work was:

- Remove `Procfile`
- Remove `app.json`
- Add `"heroku-postbuild": "npm run build"` to `package.json`
- Add empty `.static` file
- Make sure there's no `start` script in `package.json`

And that seemed to do the trick.

**Comment by josegonzalez** [comment]
Closing as what @garetmckinley did seems like a good idea :)

**Comment by justintemps** [comment]
Yea, sorry, coming back really late but @garetmckinley's solution worked great.

**Comment by ctsstc** [comment]
Seems that it expects a `start` script in `package.json` now; not sure if anything changed? @garetmckinley the example repo seems to have a `start` script in the `package.json` as well now too.

I did notice this Warning, maybe it has something to do with this?
```
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: nodejs static
```

**Comment by ctsstc** [comment]
Here's what ended up working for me. I had to run my node buildpack first, and then the static last since it will validate the static web server instead.

## Dokku Configs
```
dokku buildpacks:set APPNAME https://github.com/heroku/heroku-buildpack-nodejs.git 
dokku buildpacks:set APPNAME https://github.com/heroku/heroku-buildpack-static.git
```

## Repository Configs

#### package.json

Empty start script, so it can "call" it.

```json
{
  "scripts": {
    "build": "parcel build src/index.html src/thank-you.html --public-url ./",
    "start": ""
  }
}
```

#### static.json

```json
{
  "build": "npm run build",
  "root": "dist/"
}
```

**Comment by ShaneHudson** [comment]
The above post was really helpful thanks but note it needs `dokku buildpacks:add` instead of set
