### ISSUE TITLE
remote: curl: (7) Failed to connect to ftp.csx.cam.ac.uk port 80: Connection refused

### ISSUE THREAD

**Issue by gastonmorixe** [dokku/heroku-buildpack-nginx#32]
Solution: Create a file `.buildpacks` in your root folder of your project and add this line

```
https://github.com/dokku/buildpack-nginx.git
```

**Comment by josegonzalez** [comment]
@gastonmorixe you should upgrade your herokuish version, it is very out of date at this point.
