### ISSUE TITLE
Specify default buildpack

### ISSUE THREAD

**Issue by kculmback** [dokku/heroku-buildpack-nginx#37]
I get the following warning when trying to deploy a project using a `.static` file:
```
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: nodejs static
-----> Node.js app detected
```

While the project does utilize a `package.json` file, I do not want to serve it as a node.js app. Instead I would like to serve it as a static site. 

How do I go about setting the `static` buildpack as default when deploying?

**Comment by josegonzalez** [comment]
If this is via Dokku, please consult the [buildpack](http://dokku.viewdocs.io/dokku/deployment/methods/buildpacks/) docs for more details.
