### ISSUE TITLE
Default NGINX page post deploy.

### ISSUE THREAD

**Issue by johnnye** [dokku/heroku-buildpack-nginx#4]
It serves the standard nginx page for this application only. 

The steps at https://github.com/dokku/dokku/blob/master/docs/troubleshooting.md don't seem to apply - as the other applications on the host all work (with longer names)

Looking at the config file in the container it seems to look good, and curling the address listed in the `/home/dokku/app/nginx.conf` `http` section from the host machine works. 

Is dokku not registering the new application correctly? Or is it something to do with this applications configuration?

**Comment by josegonzalez** [comment]
Can you provide more details about the application being deployed? Specifically, please include _all_ of the info specified [here](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md). Thanks!

**Comment by johnnye** [comment]
My apologies. PEBKAC - forgot to modify some DNS settings.
