### ISSUE TITLE
Charset utf8 by default

### ISSUE THREAD

**Issue by boxed** [dokku/heroku-buildpack-nginx#40]
The nginx default for charset seems to be ascii which is rather annoying. UTF8 is a much better default.

**Comment by josegonzalez** [comment]
Pull requests welcome.

**Comment by boxed** [comment]
I don't really understand nginx configs I'm afraid. Like I found this https://jdh8.github.io/charset-for-text-on-nginx/

But I don't know if it's correct, or where I would put that code if it is. Can I just chuck it in mime.types in some random place?

**Comment by josegonzalez** [comment]
How do you know that the default character set is ascii?

**Comment by boxed** [comment]
I used this template to set up https://www.kodare.com/ and there is no mention of encoding in the response, and if I didn't add a utf8 encoding declaration in the html it got interpreted as ascii by my browser.

**Comment by boxed** [comment]
Thanks!
