### ISSUE TITLE
Building fails unknown directive "charset"

### ISSUE THREAD

**Issue by sicutdeux** [dokku/heroku-buildpack-nginx#46]
I got this error:

=====> docs web container output:
       nginx: [emerg] unknown directive "charset" in /app/nginx/nginx.conf:13
       2021/02/11 00:35:04 exit status 1
       nginx: [emerg] unknown directive "charset" in /app/nginx/nginx.conf:13
       2021/02/11 00:35:05 exit status 1
       nginx: [emerg] unknown directive "charset" in /app/nginx/nginx.conf:13
       2021/02/11 00:35:06 exit status 1
       nginx: [emerg] unknown directive "charset" in /app/nginx/nginx.conf:13
       2021/02/11 00:35:07 exit status 1
       nginx: [emerg] unknown directive "charset" in /app/nginx/nginx.conf:13
       2021/02/11 00:35:08 exit status 1
       nginx: [emerg] unknown directive "charset" in /app/nginx/nginx.conf:13
       2021/02/11 00:35:10 exit status 1
       nginx: [emerg] unknown directive "charset" in /app/nginx/nginx.conf:13
       2021/02/11 00:35:14 exit status 1

Using it with buildpack python.

**Comment by Trysystems** [comment]
Got the same error.

**Comment by paulusm** [comment]
see https://github.com/dokku/buildpack-nginx/issues/43

**Comment by josegonzalez** [comment]
Please clear your cache and rebuild.
