### ISSUE TITLE
PCRE EOL

### ISSUE THREAD

**Issue by Mejerigaarden** [dokku/heroku-buildpack-nginx#49]
## Description of problem
Trying to deploy a static site

### How reproducible
`git push staging staging`

### Steps to Reproduce

1. create a new repo
2. add .static file in root
3. push it to a docker/dokku enabled server/VM

#### Actual Results

```
√ battery.rehab % git push staging staging
Enumerating objects: 91, done.
Counting objects: 100% (91/91), done.
Delta compression using up to 8 threads
Compressing objects: 100% (76/76), done.
Writing objects: 100% (91/91), 3.18 MiB | 12.43 MiB/s, done.
Total 91 (delta 12), reused 77 (delta 6), pack-reused 0
-----> Set staging to DOKKU_DEPLOY_BRANCH.
-----> Cleaning up...
-----> Building staging.battery.rehab from herokuish
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> .static app detected
-----> Copy static files to www
-----> Download and unzip pcre 8.43 via http
remote: curl: (28) Failed to connect to ftp.pcre.org port 443: Connection timed out
remote: 2021/12/01 13:59:57 exit status 28
To docker1:staging.battery.rehab
 ! [remote rejected] staging -> staging (pre-receive hook declined)
error: failed to push some refs to 'docker1:staging.battery.rehab'

```

### Additional information

I believe the issue at hand is pertaining to this message on https://pcre.org

> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

**Comment by Mejerigaarden** [comment]
hmm - did update my buildpack-nginx along with dokku - but something else must have come between "us" - found that the latest buildpack does infact download PCRE from the right place - 

closing this issue

**Comment by josegonzalez** [comment]
Updating herokuish will fix this.

```
dokku-update run
```

That will update herokuish and rebuilt your apps. The rebuild is also necessary.
