### ISSUE TITLE
how to update heroku-buildpack-nginx ?

### ISSUE THREAD

**Issue by wdiechmann** [dokku/heroku-buildpack-nginx#50]
noticed [this issue - #49](https://github.com/dokku/heroku-buildpack-nginx/issues/49) which was closed rather quickly - but when asking on a PM it turned out that it is in fact not solved!

The reason is - no matter if you update dokku to (newest) 0.26.6 - that the heroku-buildpack-nginx is not updated.

how can I / we update that - googling it left me empty 😢

**Comment by wdiechmann** [comment]
ok - so the answer is to add a `.buildpack` file in the root of the repo with this content:

```
https://github.com/dokku/heroku-buildpack-nginx.git
```

**Comment by josegonzalez** [comment]
Thats not the correct way to update. Please update herokuish.

```
dokku-update run
```

That will update herokuish and rebuilt your apps. The rebuild is also necessary.

**Comment by wdiechmann** [comment]
@josegonzalez that is correct - but in my case I had to uninstall and then reinstall dokku to get that particular effect - but it is correct that in a fresh install the heroku-buildpack-nginx will deliver as expected

**Comment by josegonzalez** [comment]
Seems the released images were not up to date, but now they should be - was a bug in the release of 0.5.32. A reinstall should no longer be an issue, and folks should be able to upgrade to herokuish 0.5.33 and have things work.
