### ISSUE TITLE
The latest v16 release broke static projects using history routing

### ISSUE THREAD

**Issue by rtkirill** [dokku/heroku-buildpack-nginx#53]
After a couple of days of searching for the problem, I figured out why my static projects using Vue-Router start showing 404 after deploy. The reason is in the latest v16 release [using](https://github.com/dokku/heroku-buildpack-nginx/commit/6c1abc05475a5eaeb073e5efeb351f12a56d4320#diff-bb8e5746b72338033139975272747931c4a0afc14285526436acb4b8dab3598dR26) `try_files $uri $uri/ =404;` instead of `try_files $uri $uri//index.html;`

Overriding the **app-nginx.conf.sigil** file with `try_files $uri $uri//index.html;` solves my problem.

**Comment by marcinfair** [comment]
@rtkirill, thanks for opening issue. I spent 6h searching on the web until ended here and read your ticket.
I can confirm, that your solution works as expected on vue3 static page
