### ISSUE TITLE
build failure - looks like line 70 is now out of sync with line 77

### ISSUE THREAD

**Issue by walquis** [dokku/heroku-buildpack-nginx#64]
https://github.com/dokku/heroku-buildpack-nginx/blob/aa191df661c409529a0fb23cf9554292287f7e57/bin/compile#L70

The "cp -r" on line 77 fails, b/c the gliderlabs-sigil-amd64 never gets created, b/c the check for "sigil" succeeds if cached from previous deploy.

A workaround is to remove "sigil" from the cache directory.

**Comment by josegonzalez** [comment]
Mind changing the name of the file we check for to the new one?

**Comment by ezequielstx** [comment]
Problem with sigil

`remote: cp: cannot stat 'gliderlabs-sigil-amd64': No such file or directory`
